---
title: "Relatorio Parcial"
---


```{r}
#BiocManager::install("IlluminaHumanMethylationEPICanno.ilm10b4.hg19")
#BiocManager::install("missMethyl")
#BiocManager::install("minfiData")

```

```{r,message=FALSE,warning=FALSE}
library(limma)
library(minfi)
library(IlluminaHumanMethylationEPICmanifest)
library(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)
library(RColorBrewer)
library(readr)
library(maxprobes)
#tidyverse::tidyverse_packages()
#install.packages("remotes")
#remotes::install_github("markgene/maxprobes")
```

# Carregando os dados

```{r}
load("../../data/rgSetSample.rds")
```

```{r}
dim(rgSet)
```

# Passo a passo do Cross Package

## Banco de dados amostrado

```{r}
annEPIC <- getAnnotation(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)
#dim(annEPIC)
```
46 informações de 865859 ilhas.

```{r}
sampleNames(rgSet)
```
Cada uma dessas amostras apresenta os arquivos green e red

```{r}
rgSet
```

```{r}
qcReport(rgSet, pdf = "qcReport.pdf")
```

## Controle de qualidade

```{r}
detP <- data.frame(detectionP(rgSet))
```

```{r}
write.csv(detP, "../../data/pvalor.csv", row.names=T)
```

```{r}
detP = read.csv(file = "../../data/pvalor.csv", row.names = 1)
```

```{r}
png(file = "../../imagens/QCplotç.png") # defaults to 7 x 7 inches
barplot(colMeans(detP), las=2, cex.names=0.5, ylim=c(0,0.0005))
abline(h=0.00045,col="red")
dev.off()
```

```{r}
filtro_amostras <- data.frame(colMeans(detP))
filtro_amostras$amostra <- rownames(filtro_amostras); rownames(filtro_amostras) <- NULL
colnames(filtro_amostras) <- c("media", "amostra")
```

```{r}
grafico <- ggplot(filtro_amostras) +
  geom_bar(aes(x = amostra, y = media), stat = "identity", fill="#1f9e78") +
  geom_abline(slope = 0, intercept = 0.00045, color="red") +
  ylim(0, 0.0005) +
  xlab("Amostra") +
  ylab("Média") +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggsave(filename = "pvaluesMean_probes.png", plot = grafico, path = '../../imagens', height = 4)
```

Legenda do gráfico: Média dos p-valores detectados nas CpG's para cada indivíduo.

```{r}
Mset <- preprocessRaw(rgSet)
```

```{r}
plotQC(getQC(Mset))
```

### Removendo as amostras com qualidade baixa

```{r}
keep <- colMeans(detP) < 0.05
```

<!-- Manter no rgset -->

```{r}
rgSet <- rgSet[,keep]
```

<!-- Manter no detP -->

```{r}
detP <- detP[,keep]
```

## Normalização

```{r, eval=FALSE}
mSetSq <- preprocessQuantile(rgSet)
```

```{r, eval=FALSE}
save(mSetSq,file="../../data/mSetSq.rds")
```

```{r}
load("../../data/mSetSq.rds")
```

```{r}
dim(mSetSq)
```

<!-- Dados brutos e dados pré-processados na mesma figura -->

```{r,fig.width=15}
png(file = "../../imagens/densidades_preprocessQuantile.png")
par(mfrow=c(2,1))
densityPlot(rgSet,main="Dados Brutos", legend=FALSE)
densityPlot(getBeta(mSetSq),main="Dados Pré-processados", legend=FALSE)
dev.off()
```

```{r, fig.width=15}
png(file = "../../imagens/boxplots_preprocessQuantile.png")
par(mfrow=c(2,1))
boxplot(getBeta(rgSet),main="Dados Brutos", ylab="Beta", legend=FALSE, col="#1f9e78", cex.axis=0.7, las=2)
boxplot(getBeta(mSetSq),main="Dados Pré-processados", ylab="Beta", legend=FALSE, col="#1f9e78", cex.axis=0.7, las=2)
dev.off()
```

<!-- Dados brutos e dados pré-processados em figuras diferentes -->

```{r}
png(file = "../../imagens/rawData_preprocessQuantile.png")
par(mfrow=c(2,1), mai=c(1.0,.8,.5,.2))
densityPlot(rgSet, main="Dados Brutos", legend=FALSE)
boxplot(getBeta(rgSet), ylab="Beta", legend=FALSE, col="#1f9e78", cex.axis=0.7, las=2)
dev.off()
```

```{r}
png(file = "../../imagens/quantileData_preprocessQuantile.png")
par(mfrow=c(2,1), mai=c(1.0,.8,.5,.2))
densityPlot(getBeta(mSetSq),main="Dados Pré-processados", legend=FALSE)
boxplot(getBeta(mSetSq), ylab="Beta", legend=FALSE, col="#1f9e78", cex.axis=0.7, las=2)
dev.off()
```

<!-- Violin graph -->

```{r}
png(file = "../../imagens/densityBean_preprocessQuantile.png")
par(mfrow=c(1,2), mai=c(1.0,1.4,.8,.4))
densityBeanPlot(getBeta(rgSet), main = "Dados Brutos")
densityBeanPlot(getBeta(mSetSq), main = "Dados Pŕe-processados")
dev.off()
```

<!-- Demais gráficos -->

```{r}
mdsPlot(getBeta(mSetSq))
```

```{r}
controlStripPlot(rgSet)
```

<!-- Código dos gráficos utilizados na pipeline -->

```{r}
png(file = "../../imagens/densidades_preprocessQuantile.png")
par(mfrow=c(2,1))
minfi::densityPlot(rgSet,main="Dados Brutos", legend=FALSE)
minfi::densityPlot(minfi::getBeta(mSetSq),main="Dados Pré-processados", legend=FALSE)
dev.off(); gc()

png(file = "../../imagens/boxplots_preprocessQuantile.png")
par(mfrow=c(2,1))
boxplot(minfi::getBeta(rgSet),main="Dados Brutos", ylab="Beta", legend=FALSE, col="#1f9e78", cex.axis=0.7, las=2)
boxplot(minfi::getBeta(mSetSq),main="Dados Pré-processados", ylab="Beta", legend=FALSE, col="#1f9e78", cex.axis=0.7, las=2)
dev.off(); gc()

png(file = "../../imagens/densityBean_preprocessQuantile.png")
par(mfrow=c(1,2), mai=c(1.0,1.4,.8,.5))
minfi::densityBeanPlot(rgSet, main = "Dados Brutos")
minfi::densityBeanPlot(minfi::getBeta(mSetSq), main = "Dados Pŕe-processados")
dev.off(); gc()
```


## Exploração de dados

```{r}
png(file = "../../../fileName.png") # defaults to 7 x 7 inches
plotMDS(getM(mSetSq), top=1000, gene.selection="common")
dev.off()
```

```{r}
png(file = "../../../fileName2.png") # defaults to 7 x 7 inches
plotMDS(getBeta(mSetSq), top=1000, gene.selection="common", main="teste")
ylab("")
dev.off()
```

## Filtragem

<!-- Filtragem das sondas problemáticas -->

```{r}
detP <- detP[match(featureNames(mSetSq),rownames(detP)),]
```

```{r}
keep <- rowSums(detP < 0.01) == ncol(mSetSq)
table(keep)
```

```{r}
mSetSqFlt <- mSetSq[keep,]
```

```{r}
remove(mSetSq)
```

<!-- Filtragem das probes dos cromossomos de sexo -->

```{r}
keep <- !(featureNames(mSetSqFlt) %in% annEPIC$Name[annEPIC$chr %in% c("chrX","chrY")])
table(keep)
```

```{r}
mSetSqFlt <- mSetSqFlt[keep,]
```

<!-- Remove as sondas com SNP nos campos de CpG -->

```{r}
mSetSqFlt <- dropLociWithSnps(mSetSqFlt)
```

<!-- xreactive -->

```{r}
xReactiveProbes <- xreactive_probes(array_type = "EPIC")

keep <- !(featureNames(mSetSqFlt) %in% xReactiveProbes)
table(keep)
```

```{r}
mSetSqFlt <- mSetSqFlt[keep,]
```
-->

<!-- Salvando os dados finais após todos os filtros -->

```{r}
save(mSetSqFlt,file="../../data/mSetSqFlt.rds")
```

```{r}
load("../../data/mSetSqFlt.rds")
```

<!-- Pré-processamento completo -->

```{r}
##  Sondas/CpG's problemáticas (pvalor)

filtro_sondas <- function(detP, mSetSq){
  return(rowSums(detP < 0.01) == ncol(mSetSq))
}

## Filtragem das probes dos cromossomos de sexo
filtro_crsx <- function(mSetSq){
  annEPIC <- getAnnotation(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)
  keep <- !(featureNames(mSetSq) %in% annEPIC$Name[annEPIC$chr %in% c("chrX","chrY")])
  remove(annEPIC)
  return(keep)
}

## Remoção das sondas com SNP nos campos de CpGs
filtro_snp <- function(detP, mSetSq){
  return(rownames(detP) %in% rownames(dropLociWithSnps(mSetSq)))
}

## Exclusão de sondas com reatividade cruzada
filtro_reatcruz <- function(mSetSq){
  return(!(featureNames(mSetSq) %in% xreactive_probes(array_type = "EPIC")))
}

# Salvando objetos finais
save_final_obj <- function(mSetSq, detP){
  save(mSetSq,file="data/mSetSqFinal.rds")
  write.csv(detP, "data/pvaloFinal.csv", row.names=T)
}
```

```{r}
detP = read.csv(file = "../../data/pvalor.csv", row.names = 1)
load("../../data/mSetSq.rds")

detP <- detP[match(featureNames(mSetSq),rownames(detP)),]

### Filtragem das sondas
keep <- filtro_sondas(detP, mSetSq)
detP <- detP[keep,]; mSetSq <- mSetSq[keep,]
remove(keep); gc()

### Filtragem das probes dos cromossomos de sexo
keep <- filtro_crsx(mSetSq)
detP <- detP[keep,]; mSetSq <- mSetSq[keep,]

### Remoção das sondas com SNP nos campos de CpGs
keep <- filtro_snp(detP, mSetSq)
detP <- detP[keep,]; mSetSq <- mSetSq[keep,]

### Exclusão de sondas com reatividade cruzada
keep <- filtro_reatcruz(mSetSq)
detP <- detP[keep,]; mSetSq <- mSetSq[keep,]
remove(keep); gc()
```

<!-- Cálculo de M e Beta -->

```{r}
mVals <- getM(mSetSqFlt)
```

```{r}
bVals <- getBeta(mSetSqFlt)
```

```{r}
head(mVals[,1:5])
head(bVals[,1:5])
```
